before_script:
  - eval $(ssh-agent -s)
  - echo "$ssh_key" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - ssh -o StrictHostKeyChecking=no ubuntu@app sudo chown ubuntu /var/www/avt0m8.ru/ -R
    - scp -o StrictHostKeyChecking=no -r ./* ubuntu@app:/var/www/avt0m8.ru/
    - ssh -o StrictHostKeyChecking=no ubuntu@app rm -rf /var/www/avt0m8.ru/.git
    - ssh -o StrictHostKeyChecking=no ubuntu@app sudo chown www-data /var/www/avt0m8.ru/ -R
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/'