# Создаем файл inventory.yml для последующего запуска ansible
resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    ---
    nginx:
      hosts:
        ${yandex_compute_instance.nginx[0].network_interface[0].nat_ip_address}:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
          virtual_domain: ${var.fqdn}

    dbservers:
      hosts:
        db01:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.nginx[0].network_interface[0].nat_ip_address}"
          mysql_replication_role: 'master'
          
        db02:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.nginx[0].network_interface[0].nat_ip_address}"
          mysql_replication_role: 'slave'

    wordpress:
      hosts:
        app:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.nginx[0].network_interface[0].nat_ip_address}"
          virtual_domain: ${var.fqdn}

    git:
      hosts:
        gitlab:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.nginx[0].network_interface[0].nat_ip_address}"
          virtual_domain: ${var.fqdn}

    run:
      hosts:
        runner:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.nginx[0].network_interface[0].nat_ip_address}"
          virtual_domain: ${var.fqdn}

    mon:
      hosts:
        monitoring:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.nginx[0].network_interface[0].nat_ip_address}"
    DOC
  filename = "../ansible/inventory.yml"
  file_permission = "0644"

  depends_on = [yandex_compute_instance.nginx]
}
