- name: Install Nginx Web Server
  apt:
    name=nginx
    state=latest
  notify:
    - nginx systemd

- name: Replace default site
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/sites-enabled/default
  notify:
    - nginx restart

- name: Install PHP Extensions
  apt: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"

- name: Purge Apache2
  apt:
    name=apache2
    state=absent
    purge=yes

- name: Create document root
  file:
    path: "/var/www/{{ virtual_domain }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ virtual_domain }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "/var/www/{{ virtual_domain }}/wp-admin"

- name: Set ownership
  file:
    path: "/var/www/{{ virtual_domain }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ virtual_domain }}/ -type d -exec chmod 755 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ virtual_domain }}/ -type f -exec chmod 644 {} \\;"

- name: Set up wp-config
  template:
    src: "templates/wp-config.php.j2"
    dest: "/var/www/{{ virtual_domain }}/wp-config.php"

- name: Restart nginx, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted
