- hosts: nginx
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - nginx
   - nodeexporter
  vars:
    nginx_user: www-data

- hosts: dbservers
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - mysql
   - nodeexporter

- hosts: wordpress
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - wordpress
   - nodeexporter

- hosts: git
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - gitlab

- hosts: mon
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - monitoring
   - nodeexporter

- hosts: nginx
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  tasks:
    - name: nginx restart
      service:
        name=nginx
        state=restarted
    - name: Print message
      debug:
        msg: "All done."
