---
- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Install GitLab dependencies.
  apt: name={{ item }} update_cache=yes state=present
  loop: "{{ gitlab_modules }}"

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_file.stat.exists

- name: Install GitLab
  apt:
    name: "{{ gitlab_edition }}"
    state: present
  when: not gitlab_file.stat.exists

- name: modify url
  lineinfile:
     path: /etc/gitlab/gitlab.rb
     search_string: "external_url 'http://gitlab.example.com'"
     line: "external_url 'http://gitlab.{{ virtual_domain }}'"
     backup: yes

- name: modify root pass
  lineinfile:
     path: /etc/gitlab/gitlab.rb
     search_string: "gitlab_rails['initial_root_password']"
     line: "gitlab_rails['initial_root_password'] = '4a801339-a339-49f1-b458-145938e0d683'"
     backup: yes

- name: modify node_exporter
  lineinfile:
     path: /etc/gitlab/gitlab.rb
     search_string: "node_exporter['listen_address']"
     line: "node_exporter['listen_address'] = '0.0.0.0:9100'"
     backup: yes

- name: modify prometheus
  lineinfile:
     path: /etc/gitlab/gitlab.rb
     search_string: "prometheus['listen_address']"
     line: "prometheus['listen_address'] = '0.0.0.0:9090'"
     backup: yes

- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false
